### PR TITLE
Adjust for latest GDNative changes

### LINKED ISSUE #1: Can't build with latest godot git version...
I'm getting this error: 

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o src/godot_openhmd.os -c -DOHMD_STATIC -DDRIVER_OCULUS_RIFT -DDRIVER_DEEPOON -DDRIVER_HTC_VIVE -DDRIVER_PSVR -DDRIVER_NOLO -fPIC -g -O3 -std=c++14 -fPIC -DOHMD_STATIC -Ilibusb -Ilibusb/libusb -Ilibusb/libusb/os -Ihidapi/hidapi -Iopenhmd/include -I. -I/RAID/atomo/home/rhradec/dev/godot.git/modules/gdnative/include -Iglad src/godot_openhmd.c
cc1: warning: command line option '-std=c++14' is valid for C++/ObjC++ but not for C
src/godot_openhmd.c: In function 'get_openhmd_data':
src/godot_openhmd.c:47:21: error: 'godot_gdnative_api_struct {aka const struct godot_gdnative_api_struct}' has no member named 'godot_alloc'
   openhmd_data = api->godot_alloc(sizeof(openhmd_data_struct));
                     ^~
src/godot_openhmd.c: In function 'release_openhmd_data':
src/godot_openhmd.c:75:7: error: 'godot_gdnative_api_struct {aka const struct godot_gdnative_api_struct}' has no member named 'godot_free'
    api->godot_free(openhmd_data);
```

examining the godot headers, the godot_alloc() is indeed defined there... so not sure what's going on! 

I'll keep digging, but any help would be greatly appreciated! 

cheers...
-H

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This should fix #1

### CODE REVIEW

**Comment by hradec** [comment]
Thank you so much! really appreciated! 

I forgot to mention: posix is case-sensitive, so I had to create a symbolic link of OpenHMD to openhmd to be able to build. 

after that, it went through without issues! 

now I need to figure WHERE to drop the "demo" folder so Godot can pick it up! LOL

cheers...
-H

**Comment by BastiaanOlij** [comment]
For the Godot editor you just import the demo folder, it can remain where it is :)

**Comment by BastiaanOlij** [comment]
Feel free to fork this repo and submit PRs for any fixes you deem needed. I could use the hand :)

**Comment by hradec** [comment]
> Feel free to fork this repo and submit PRs for any fixes you deem needed. I could use the hand :)

Cool... Doing it now! 

btw, I managed to run the demo project, but I'm getting this error: 
image

Am I doing something wrong or this is code related?

**Comment by BastiaanOlij** [comment]
Hey @hradec,

Hmm, weird, that is this method it's trying to call:
https://github.com/BastiaanOlij/godot_openhmd/blob/master/src/godot_openhmd.c#L734

The method name should be prefixed by this:
https://github.com/BastiaanOlij/godot_openhmd/blob/master/demo/bin/godot_openhmd.gdnlib#L5

And that did work for me in the openvr branch.

**Comment by hradec** [comment]
Hummm.. Do you think it could be related to the GCC version I'm using? 
As I'm running Arch linux, I'm running GCC 7.2.0.

I did compile boot Godot and Godot_OpenHMD with the same GCC 7.2.0, so it should be fine... but maybe there's something to be changed on how the symbols are being exported?!

**Comment by BastiaanOlij** [comment]
I would expect GDNative to complain about the other functions as well. I'll have a closer look once I'm home tonight. Hopefully Karroffel will be online then as well. 

I work on Windows and Mac mostly so not sure what GCC does/doesn't do. Though Microsoft C compiler is a dog, MS flat out refuses to adopt the latest C standards telling people they're only interested in updating their C++ compilers it seems...

**Comment by hradec** [comment]
>  Do you think it could be related to the GCC version I'm using?

Ok... to verify the GCC version possibility, I've built your latest  godot_openvr  repository, and that one loads up fine! 

Although, as my SteamVR is not currently working at all in linux, I can't verify if it's tracking correctly or not... but at least it loads up fine in Godot, and shows up the demo little table perfectly. 

So... not a GCC issue, apparently... 

I'll keep digging as well, and let you known if I find something! 

cheers mate!
-H

**Comment by BastiaanOlij** [comment]
Oooowh progress! Cool!

There must be a typo in there somewhere :)

**Comment by hradec** [comment]
Some more progress:  :)

I've found this in the console, after I started godot manually from the shell:
image

sooo... it seems the hidapi `hid_get_product_string` code is not getting into libopenhmd.so.

I did a `ldd libgodot_openhmd.so` and this is the result: 
image

so it's not linked to  either `libhidapi-hidraw.so` or `libhidapi-libusb.so`.

**Comment by BastiaanOlij** [comment]
@hradec yes indeed, great writeup. This really needs to change. The reason these libraries are statically linked in through the scons file (and its really a hack on my part) is that life for this started as a module to Godot and Godot never supported dynamically linking in libraries like these before GDNative.

It is very possibly I missed a few things in that compilation for Linux as I only work on Windows and Mac.

Now that we're using GDNative we should really properly compile these dependencies using whatever mechanism their developers designed and just link with the resulting library that loads the appropriate dynamic library. 

If you look at the godot_openhmd.gdnlib file you'll see there is a new section to name the dependencies. This doesn't do anything more then tell Godot that does files need to be packages along when exporting a game.

**Comment by hradec** [comment]
> yes indeed, great writeup. 

Thanks

> he reason these libraries are statically linked in through the scons file (and its really a hack on my part) is that life for this started as a module to Godot and Godot never supported dynamically linking in libraries like these before GDNative.

Fair enough! 

> Now that we're using GDNative we should really properly compile these dependencies using whatever mechanism their developers designed and just link with the resulting library that loads the appropriate dynamic library.
> If you look at the godot_openhmd.gdnlib file you'll see there is a new section to name the dependencies. This doesn't do anything more then tell Godot that does files need to be packages along when exporting a game.

Great! I'll get to it right away! Hopefully by using the shared libraries of those dependencies will fix this "weirdeness"! 

thanks for the help man!! 
Cheers...
-H

**Comment by BastiaanOlij** [comment]
Yeah I think compiling these dependencies the way they were intended to be compiled solves a lot of issue, I need to have but a define wrong and it falls apart. I remember having to do a few really ugly things just to get them to work and that may have been on an older version.

Thank you for helping out, its nice to have other people looking at this too. I've got my hands full at the moment so :)

**Pull request merged**
